email = "studyabroadops@collegedunia.com"
password = "collegedunia123"
country = "India"
states = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunāchal Pradesh",
    "Assam",
    "Bihār",
    "Chandīgarh",
    "Chhattīsgarh",
    "Dādra and Nagar Haveli and Damān and Diu",
    "Delhi",
    "Goa",
    "Gujarāt",
    "Haryāna",
    "Himāchal Pradesh",
    "Jammu and Kashmīr",
    "Jhārkhand",
    "Karnātaka",
    "Kerala",
    "Ladākh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Mahārāshtra",
    "Manipur",
    "Meghālaya",
    "Mizoram",
    "Nāgāland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rājasthān",
    "Sikkim",
    "Tamil Nādu",
    "Telangāna",
    "Tripura",
    "Uttar Pradesh",
    "Uttarākhand",
    "West Bengal",
]
